# Generated by Django 5.1.4 on 2024-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
