# Generated by Django 5.1.4 on 2024-12-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
