# Generated by Django 5.1.4 on 2024-12-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-slug'),
            preserve_default=False,
        ),
    ]
