# Generated by Django 5.1.4 on 2024-12-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0009_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
