# Generated by Django 5.1.4 on 2024-12-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0014_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
